# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 320)
        Dialog.setAutoFillBackground(True)
        Dialog.setStyleSheet("")
        self.comboBoxDirs = QtWidgets.QComboBox(Dialog)
        self.comboBoxDirs.setGeometry(QtCore.QRect(10, 10, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.comboBoxDirs.setFont(font)
        self.comboBoxDirs.setObjectName("comboBoxDirs")
        self.comboBoxConfigs = QtWidgets.QComboBox(Dialog)
        self.comboBoxConfigs.setGeometry(QtCore.QRect(150, 10, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.comboBoxConfigs.setFont(font)
        self.comboBoxConfigs.setObjectName("comboBoxConfigs")
        self.pushButtonLoad = QtWidgets.QPushButton(Dialog)
        self.pushButtonLoad.setGeometry(QtCore.QRect(400, 0, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonLoad.setFont(font)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.pushButtonVoltage = QtWidgets.QPushButton(Dialog)
        self.pushButtonVoltage.setGeometry(QtCore.QRect(30, 80, 50, 50))
        self.pushButtonVoltage.setStyleSheet(" background-color: red;\n"
" border-style: solid;\n"
" border-radius:25px;\n"
" max-width:50px;\n"
" max-height:50px;\n"
" min-width:50px;\n"
" min-height:50px;")
        self.pushButtonVoltage.setText("")
        self.pushButtonVoltage.setObjectName("pushButtonVoltage")
        self.pushButtonCurrent = QtWidgets.QPushButton(Dialog)
        self.pushButtonCurrent.setGeometry(QtCore.QRect(120, 80, 50, 50))
        self.pushButtonCurrent.setStyleSheet(" background-color: red;\n"
" border-style: solid;\n"
" border-radius:25px;\n"
" max-width:50px;\n"
" max-height:50px;\n"
" min-width:50px;\n"
" min-height:50px;")
        self.pushButtonCurrent.setText("")
        self.pushButtonCurrent.setObjectName("pushButtonCurrent")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(110, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButtonALL = QtWidgets.QPushButton(Dialog)
        self.pushButtonALL.setGeometry(QtCore.QRect(20, 200, 100, 100))
        self.pushButtonALL.setStyleSheet(" background-color: red;\n"
" border-style: solid;\n"
" border-radius:50px;\n"
" max-width:100px;\n"
" max-height:100px;\n"
" min-width:100px;\n"
" min-height:100px;")
        self.pushButtonALL.setText("")
        self.pushButtonALL.setObjectName("pushButtonALL")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 170, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(210, 220, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(210, 240, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.labelAdditionalInfo = QtWidgets.QLabel(Dialog)
        self.labelAdditionalInfo.setGeometry(QtCore.QRect(200, 80, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelAdditionalInfo.setFont(font)
        self.labelAdditionalInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAdditionalInfo.setObjectName("labelAdditionalInfo")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(140, 290, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.CurrentDeviationLabel = QtWidgets.QLabel(Dialog)
        self.CurrentDeviationLabel.setGeometry(QtCore.QRect(360, 290, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.CurrentDeviationLabel.setFont(font)
        self.CurrentDeviationLabel.setObjectName("CurrentDeviationLabel")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(200, 170, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(200, 190, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.labelVoltageMeasured = QtWidgets.QLabel(Dialog)
        self.labelVoltageMeasured.setGeometry(QtCore.QRect(380, 220, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelVoltageMeasured.setFont(font)
        self.labelVoltageMeasured.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelVoltageMeasured.setObjectName("labelVoltageMeasured")
        self.labelCurrentMeasured = QtWidgets.QLabel(Dialog)
        self.labelCurrentMeasured.setGeometry(QtCore.QRect(380, 240, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCurrentMeasured.setFont(font)
        self.labelCurrentMeasured.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCurrentMeasured.setObjectName("labelCurrentMeasured")
        self.labelSetCurrentTo_2 = QtWidgets.QLabel(Dialog)
        self.labelSetCurrentTo_2.setGeometry(QtCore.QRect(450, 240, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelSetCurrentTo_2.setFont(font)
        self.labelSetCurrentTo_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelSetCurrentTo_2.setObjectName("labelSetCurrentTo_2")
        self.labelSetCurrentTo_3 = QtWidgets.QLabel(Dialog)
        self.labelSetCurrentTo_3.setGeometry(QtCore.QRect(450, 220, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelSetCurrentTo_3.setFont(font)
        self.labelSetCurrentTo_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelSetCurrentTo_3.setObjectName("labelSetCurrentTo_3")
        self.labelSetCurrentTo_4 = QtWidgets.QLabel(Dialog)
        self.labelSetCurrentTo_4.setGeometry(QtCore.QRect(450, 190, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelSetCurrentTo_4.setFont(font)
        self.labelSetCurrentTo_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelSetCurrentTo_4.setObjectName("labelSetCurrentTo_4")
        self.labelSetCurrentTo_5 = QtWidgets.QLabel(Dialog)
        self.labelSetCurrentTo_5.setGeometry(QtCore.QRect(450, 170, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelSetCurrentTo_5.setFont(font)
        self.labelSetCurrentTo_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelSetCurrentTo_5.setObjectName("labelSetCurrentTo_5")
        self.labelSetVoltageTo = QtWidgets.QLabel(Dialog)
        self.labelSetVoltageTo.setGeometry(QtCore.QRect(380, 170, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelSetVoltageTo.setFont(font)
        self.labelSetVoltageTo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSetVoltageTo.setObjectName("labelSetVoltageTo")
        self.labelSetCurrentTo = QtWidgets.QLabel(Dialog)
        self.labelSetCurrentTo.setGeometry(QtCore.QRect(380, 190, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelSetCurrentTo.setFont(font)
        self.labelSetCurrentTo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSetCurrentTo.setObjectName("labelSetCurrentTo")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(140, 260, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.VoltageDeviationLabel = QtWidgets.QLabel(Dialog)
        self.VoltageDeviationLabel.setGeometry(QtCore.QRect(360, 260, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.VoltageDeviationLabel.setFont(font)
        self.VoltageDeviationLabel.setObjectName("VoltageDeviationLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonLoad.setText(_translate("Dialog", "Load"))
        self.label_3.setText(_translate("Dialog", "VOLTAGE"))
        self.label_4.setText(_translate("Dialog", "CURRENT"))
        self.label_7.setText(_translate("Dialog", "TEST OK?"))
        self.label_8.setText(_translate("Dialog", "VOLTAGE MEASURED:"))
        self.label_9.setText(_translate("Dialog", "CURRENT MEASURED:"))
        self.labelAdditionalInfo.setText(_translate("Dialog", "LOREM IPSUM \n"
"TRELE MORELE"))
        self.label_13.setText(_translate("Dialog", "Current Deviation"))
        self.CurrentDeviationLabel.setText(_translate("Dialog", "10%"))
        self.label_10.setText(_translate("Dialog", "SET VOLTAGE TO:"))
        self.label_11.setText(_translate("Dialog", "SET CURRENT TO:"))
        self.labelVoltageMeasured.setText(_translate("Dialog", "asd"))
        self.labelCurrentMeasured.setText(_translate("Dialog", "asd"))
        self.labelSetCurrentTo_2.setText(_translate("Dialog", "mA"))
        self.labelSetCurrentTo_3.setText(_translate("Dialog", "V"))
        self.labelSetCurrentTo_4.setText(_translate("Dialog", "mA"))
        self.labelSetCurrentTo_5.setText(_translate("Dialog", "V"))
        self.labelSetVoltageTo.setText(_translate("Dialog", "asd"))
        self.labelSetCurrentTo.setText(_translate("Dialog", "asd"))
        self.label_14.setText(_translate("Dialog", "Voltage Deviation"))
        self.VoltageDeviationLabel.setText(_translate("Dialog", "10%"))

